---
- hosts: localhost
  remote_user: root
  become: true
  become_method: su

  vars:
      ansible_python_interpreter: '/usr/bin/python3'
  roles:
  - base
  - nvidia
  - 'multimedia-tools'
  - davinci_resolve
